version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - "./htdocs:/var/www/localhost"
            - "./logs/nginx:/var/log/nginx"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - "php"
            - "mysql-server"
    mysql-server:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=myappdb
            - MYSQL_ROOT_PASSWORD=topsecret
            - MYSQL_USER=user
            - MYSQL_PASSWORD=secret
        ports:
            - "3306:3306"
        volumes:
            - "./data/mysql:/var/lib/mysql"
    php:
        build:
            context: ./docker
            dockerfile: php-fpm/Dockerfile
        restart: always
        volumes:
            - "./htdocs:/var/www/localhost"
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
